mp_id: mp-3953

globals:
  duration: 10.0   # should be able to read in MP data without specifying duration, so this can be overridden at job level.
  temp: null # should also be able to specify multiple temps (I think this would break it currently?)
  lfo: true
  lfo_target: volume
  overwrite: false

jobs:
  - name: one
    mode: choral
    site: Ca_1

  - name: two
    mode: choral
    site: C_1

  - name: three
    mode: spectral
    site: Ca_1

mix:
  output: super_again_low.wav
  overwrite: true
  quiet: true
  fade: 2.0          # make this specify how mix between stages
  curve: tri         # make this specify how mix between stages
  mode: compose  # super, concat, compose
  composition:
    - type: concat
      order: [one, two, three]  # do option for random order of given length
      fade: 2.0 
      
    - type: super
      weights:
        one: 1.0   
        two: 1.0
        three: 0.0
        normalise: true

    - type: concat
      order: [one, two]
      fade: 3.0
      
