mp_id: mp-66
globals:
  duration: 5.0   # should be able to read in MP data without specifying duration, so this can be overridden at job level, change needed to phonon sonification module
  temp: null # should also be able to specify multiple temps here, and then jobs could be at one of a selection of thse (I think this would break it currently?)
  lfo: true
  lfo_target: volume
  overwrite: yes
  fmin_phonon: 1.7E10
  fmax_phonon: 4.8E13

jobs:

  - name: one
    mode: choral
    sites: all


